# Generated by Django 5.0.6 on 2024-06-19 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PoolHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveIntegerField()),
                ('opponents_met', models.PositiveIntegerField()),
                ('games_won', models.PositiveIntegerField()),
                ('inviting_to_play', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile-pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('after_outdated', models.BooleanField(default=False)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='poolstore.matchup')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='poolstore.player')),
            ],
        ),
        migrations.AddField(
            model_name='matchup',
            name='player_accepting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_matchups', to='poolstore.player'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='player_inviting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_matchup_invitings', to='poolstore.player'),
        ),
        migrations.CreateModel(
            name='MatchMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmakings', to='poolstore.player')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='poolstore.player')),
                ('player_inviting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='poolstore.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolstore.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolstore.player')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(related_name='game_session', through='poolstore.PlayerGameSession', to='poolstore.player'),
        ),
        migrations.CreateModel(
            name='PoolTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poolhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='poolstore.poolhouse')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='pooltable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to='poolstore.pooltable'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.PositiveSmallIntegerField(default=30)),
                ('end_time', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='poolstore.player')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='poolstore.pooltable')),
            ],
        ),
    ]
