# Generated by Django 5.1.2 on 2024-11-07 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoolHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('room_image', models.ImageField(null=True, upload_to='poolhouses')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveIntegerField()),
                ('opponents_met', models.PositiveIntegerField()),
                ('games_won', models.PositiveIntegerField()),
                ('inviting_to_play', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile-pics')),
                ('total_points', models.PositiveIntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='poolstore.player')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('after_outdated', models.BooleanField(default=False)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='poolstore.matchup')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='poolstore.player')),
            ],
        ),
        migrations.AddField(
            model_name='matchup',
            name='player_accepting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_matchups', to='poolstore.player'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='player_inviting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_matchup_invitings', to='poolstore.player'),
        ),
        migrations.CreateModel(
            name='MatchMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmakings', to='poolstore.player')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationDenied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player_denied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denied_invitations', to='poolstore.player')),
                ('player_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolstore.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolstore.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolstore.player')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(related_name='game_session', through='poolstore.PlayerGameSession', to='poolstore.player'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_winner', models.PositiveSmallIntegerField(null=True)),
                ('result_loser', models.PositiveSmallIntegerField(null=True)),
                ('points_given', models.PositiveSmallIntegerField(null=True)),
                ('penalty_points', models.PositiveSmallIntegerField(null=True)),
                ('tie', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('loser_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss_history', to='poolstore.player')),
                ('winner_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_history', to='poolstore.player')),
                ('poolhouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_history', to='poolstore.poolhouse')),
            ],
        ),
        migrations.CreateModel(
            name='PoolHouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='poolhall-pics')),
                ('poolhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='poolstore.poolhouse')),
            ],
        ),
        migrations.CreateModel(
            name='PoolHouseStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poolhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='poolstore.poolhouse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoolTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(null=True)),
                ('free', models.BooleanField(default=True)),
                ('poolhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='poolstore.poolhouse')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='pooltable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to='poolstore.pooltable'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField(default=30)),
                ('end_time', models.DateTimeField()),
                ('real_end_datetime', models.DateTimeField()),
                ('finished_reservation', models.BooleanField(default=False)),
                ('other_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_reservations', to='poolstore.player')),
                ('player_reserving', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_reservations', to='poolstore.player')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='poolstore.pooltable')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='matchup',
            unique_together={('player_accepting', 'player_inviting')},
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='poolstore.player')),
                ('player_inviting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='poolstore.player')),
            ],
            options={
                'unique_together': {('player_invited', 'player_inviting')},
            },
        ),
        migrations.CreateModel(
            name='PoolHouseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField()),
                ('review', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('poolhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='poolstore.poolhouse')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_ratings', to='poolstore.player')),
            ],
            options={
                'unique_together': {('rater', 'poolhouse')},
            },
        ),
    ]
