# Generated by Django 5.1.2 on 2024-11-07 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['inviting_to_play'], name='poolstore_p_invitin_983c36_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['total_points', 'inviting_to_play'], name='poolstore_p_total_p_512e1e_idx'),
        ),
    ]
