# Generated by Django 5.0.6 on 2024-06-15 15:22

import datetime
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='real_end_time',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('end_time'), '+', models.Value(datetime.timedelta(seconds=300))), output_field=models.DateTimeField()),
        ),
    ]
