# Generated by Django 5.0.6 on 2024-06-07 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='id',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='id',
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
