# Generated by Django 5.0.6 on 2024-06-19 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='real_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
