# Generated by Django 5.0.3 on 2024-04-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0002_alter_gamesession_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmakings', to='poolstore.player')),
            ],
        ),
    ]
