# Generated by Django 5.1.1 on 2024-10-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0002_reservation_matchup_alter_player_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolhouse',
            name='latitude',
            field=models.FloatField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolhouse',
            name='longitude',
            field=models.FloatField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='finished_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='loser_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss_history', to='poolstore.player'),
        ),
        migrations.AlterField(
            model_name='history',
            name='penalty_points',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='points_given',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='result_loser',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='result_winner',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='matchup',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='poolstore.matchup'),
        ),
    ]
