# Generated by Django 5.0.6 on 2024-06-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0002_reservation_real_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolhouse',
            name='close_hour',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolhouse',
            name='open_hour',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
