# Generated by Django 5.1.1 on 2024-10-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0003_poolhouse_latitude_poolhouse_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolhouserating',
            name='review',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
