# Generated by Django 5.0.3 on 2024-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0003_matchmake'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inviting_to_play',
            field=models.BooleanField(default=False),
        ),
    ]
