# Generated by Django 5.1.3 on 2024-11-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0003_player_lat_player_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='extra',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poolstore.player'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PEN', 'Invited'), ('APP', 'Rejected'), ('REJ', 'Accepted'), ('MSG', 'Message')], default=2, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(default='profile-pics/default.jpg', upload_to='profile-pics'),
        ),
    ]
