# Generated by Django 5.0.3 on 2024-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0004_player_inviting_to_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolhouse',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
