# Generated by Django 5.1.3 on 2024-11-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0004_remove_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PEN', 'Invited'), ('REJ', 'Rejected'), ('ACP', 'Accepted'), ('MSG', 'Message')], max_length=3),
        ),
    ]
