# Generated by Django 5.1.1 on 2024-09-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0004_reservation_real_end_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
