# Generated by Django 5.1.1 on 2024-10-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0004_poolhouserating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooltable',
            name='table_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
