# Generated by Django 5.1.3 on 2024-11-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INV', 'Invited'), ('REJ', 'Rejected'), ('ACP', 'Accepted'), ('MSG', 'Message')], max_length=3),
        ),
    ]
