# Generated by Django 5.0.3 on 2024-04-11 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0005_alter_poolhouse_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_player', to='poolstore.player')),
                ('player_inviting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviting_player', to='poolstore.player')),
            ],
        ),
    ]
