# Generated by Django 5.0.3 on 2024-04-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0006_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='player_invited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='poolstore.player'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='player_inviting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='poolstore.player'),
        ),
        migrations.CreateModel(
            name='Matchups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_accepting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_matchups', to='poolstore.player')),
                ('player_inviting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_matchup_invitings', to='poolstore.player')),
            ],
        ),
    ]
