# Generated by Django 5.1.1 on 2024-09-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0006_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
