# Generated by Django 5.1.3 on 2024-11-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INV', 'Invited'), ('REJ', 'Rejected'), ('ACP', 'Accepted')], max_length=3),
        ),
    ]
