# Generated by Django 5.1.1 on 2024-10-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0006_alter_pooltable_table_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='matchup',
        ),
    ]
