# Generated by Django 5.0.3 on 2024-04-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0007_alter_invitation_player_invited_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matchups',
            new_name='Matchup',
        ),
    ]
