# Generated by Django 5.1.1 on 2024-09-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0007_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolHouseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField()),
                ('poolhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='poolstore.poolhouse')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_ratings', to='poolstore.player')),
            ],
        ),
    ]
