# Generated by Django 5.1.3 on 2024-11-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0008_matchup_read'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['time_sent'], name='poolstore_m_time_se_af4b09_idx'),
        ),
    ]
