# Generated by Django 5.0.3 on 2024-04-22 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0008_rename_matchups_matchup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
