# Generated by Django 5.1.1 on 2024-10-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0009_rename_player_reservation_player_reserving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='other_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_reservations', to='poolstore.player'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='player_reserving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reservations', to='poolstore.player'),
        ),
    ]
