# Generated by Django 5.1.3 on 2024-12-15 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0009_message_poolstore_m_time_se_af4b09_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolhouse',
            name='close_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolhouse',
            name='open_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pooltable',
            name='left',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pooltable',
            name='top',
            field=models.FloatField(default=0.0),
        ),
    ]
