# Generated by Django 5.0.4 on 2024-04-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0009_alter_matchup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='player_waiting',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='poolstore.player'),
        ),
    ]
