# Generated by Django 5.1.1 on 2024-09-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0009_remove_gamesession_result_player_total_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='status_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
