# Generated by Django 5.1.4 on 2025-01-05 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0010_poolhouse_close_time_poolhouse_open_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='in_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INV', 'Invited'), ('REJ', 'Rejected'), ('ACP', 'Accepted'), ('GSE', 'Game Session End')], max_length=3),
        ),
    ]
