# Generated by Django 5.1.1 on 2024-10-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0010_alter_reservation_other_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='poolhouse',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='status_finished',
        ),
    ]
