# Generated by Django 5.1.1 on 2024-09-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0010_gamesession_status_finished_alter_history_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='poolhouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='house_game_sessions', to='poolstore.poolhouse'),
            preserve_default=False,
        ),
    ]
