# Generated by Django 5.1.1 on 2024-10-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0011_remove_gamesession_poolhouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolHouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='poolhall-pics')),
                ('poolhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='poolstore.poolhouse')),
            ],
        ),
    ]
