# Generated by Django 5.1.4 on 2025-01-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0011_gamesession_start_time_reservation_in_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INV', 'Invited'), ('REJ', 'Rejected'), ('ACP', 'Accepted'), ('GSE', 'Game Session End'), ('GSEA', 'Game Session End Alone')], max_length=4),
        ),
    ]
