# Generated by Django 5.0.4 on 2024-04-30 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0011_remove_matchup_player_waiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='poolstore.matchup')),
            ],
        ),
    ]
