# Generated by Django 5.0.4 on 2024-05-05 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
