# Generated by Django 5.1.1 on 2024-10-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0012_poolhouseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='status_finished',
            field=models.BooleanField(default=False),
        ),
    ]
