# Generated by Django 5.1.5 on 2025-01-29 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0012_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolhouserating',
            name='rate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
