# Generated by Django 5.1.5 on 2025-02-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0013_alter_poolhouserating_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchMake',
        ),
    ]
