# Generated by Django 5.1.5 on 2025-02-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0014_delete_matchmake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INV', 'Invited'), ('REJ', 'Rejected'), ('ACP', 'Accepted'), ('GSE', 'Game Session End'), ('GSEA', 'Game Session End Alone'), ('SPW', 'Set password')], max_length=4),
        ),
    ]
