# Generated by Django 5.0.4 on 2024-05-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0014_alter_message_time_sent_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
