# Generated by Django 5.1.1 on 2024-10-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0015_poolhousestaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolhouserating',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
