# Generated by Django 5.1.2 on 2024-10-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0016_poolhouserating_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooltable',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
