# Generated by Django 5.0.5 on 2024-05-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0017_player_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile-pics'),
        ),
    ]
