# Generated by Django 5.1.2 on 2024-10-31 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0017_pooltable_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='player_reserving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_reservations', to='poolstore.player'),
        ),
    ]
