# Generated by Django 5.0.5 on 2024-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0018_alter_player_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='outdated',
            field=models.BooleanField(default=False),
        ),
    ]
