# Generated by Django 5.1.2 on 2024-11-07 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0019_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationDenied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player_denied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denied_invitations', to='poolstore.player')),
                ('player_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolstore.player')),
            ],
        ),
    ]
