# Generated by Django 5.0.5 on 2024-05-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0019_message_outdated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='outdated',
            new_name='after_outdated',
        ),
    ]
