# Generated by Django 5.1.2 on 2024-11-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0020_invitationdenied'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('player_invited', 'player_inviting')},
        ),
    ]
