# Generated by Django 5.0.5 on 2024-05-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0021_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
