# Generated by Django 5.1.2 on 2024-11-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0021_alter_invitation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchup',
            unique_together={('player_accepting', 'player_inviting')},
        ),
    ]
