# Generated by Django 5.1.2 on 2024-11-07 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0022_alter_matchup_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['total_points'], name='poolstore_p_total_p_70ea13_idx'),
        ),
    ]
