# Generated by Django 5.0.5 on 2024-05-13 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0022_remove_message_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponents', to='poolstore.player')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poolstore.player')),
            ],
        ),
    ]
