# Generated by Django 5.0.5 on 2024-05-13 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0023_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opponent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolstore.player'),
        ),
    ]
