# Generated by Django 5.1.2 on 2024-11-07 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0023_player_poolstore_p_total_p_70ea13_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='poolstore_p_total_p_70ea13_idx',
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['total_points', 'inviting_to_play'], name='poolstore_p_total_p_512e1e_idx'),
        ),
    ]
