# Generated by Django 5.0.5 on 2024-05-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0024_alter_opponent_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opponent',
        ),
    ]
