# Generated by Django 5.0.6 on 2024-05-21 09:42

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0026_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='poolstore.pooltable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='real_end_time',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('end_time'), '+', models.Value(datetime.timedelta(seconds=300))), output_field=models.TimeField()),
        ),
    ]
