# Generated by Django 5.0.6 on 2024-05-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0027_reservation_table_reservation_real_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
