# Generated by Django 5.0.6 on 2024-05-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolstore', '0029_reservation_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='real_end_time',
        ),
    ]
